### ISSUE TITLE
Principio de Minima Sorpresa -> Principio de Acceso Uniforme

### ISSUE THREAD

**Issue by aranajuan** [LosYakuza/jrpg-2017a-dominio#7]
Principio de Minima Sorpresa -> Principio de Acceso Uniforme 
setFuerza(10 + casta.getFuerza()); 
inteligencia = 10 + casta.getInteligencia(); 
destreza = 10 + casta.getDestreza();

**Comment by aranajuan** [comment]
@mramirez96 que hay que hacer acá?

**Comment by mramirez96** [comment]
Acceder a los atributos de la misma manera. O por el atributo directamente o por el setter.
